# Generated by Django 5.2.7 on 2025-11-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(help_text='Уникальный идентификатор для ссылки в Excel', max_length=50, unique=True, verbose_name='ID файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('3d_model', '3D Модель')], max_length=20, verbose_name='Тип файла')),
                ('file', models.FileField(upload_to='assets/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файловый ресурс',
                'verbose_name_plural': 'Файловые ресурсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image_asset_ids',
            field=models.CharField(blank=True, help_text='ID изображений через запятую (например: img_001,img_002)', max_length=500, verbose_name='ID изображений'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_asset_ids',
            field=models.CharField(blank=True, help_text='ID 3D моделей через запятую (например: model_001,model_002)', max_length=500, verbose_name='ID 3D моделей'),
        ),
    ]
