# Generated by Django 5.2.7 on 2025-12-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_fileasset_product_image_asset_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=120, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_ar_glb',
            field=models.CharField(blank=True, max_length=500, verbose_name='AR-GLB файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_fbx',
            field=models.CharField(blank=True, max_length=500, verbose_name='FBX файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_glb',
            field=models.CharField(blank=True, max_length=500, verbose_name='GLB файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_rfa',
            field=models.CharField(blank=True, max_length=500, verbose_name='RFA файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_usdz',
            field=models.CharField(blank=True, max_length=500, verbose_name='USDZ файл'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=120, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=60, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='В тренде'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=120, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=120, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
