# Generated by Django 5.2.7 on 2026-02-23 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_set_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='cp_image',
            field=models.ImageField(blank=True, help_text='Изображение товара, отображается только в коммерческом предложении', null=True, upload_to='products/cp/', verbose_name='Фото для КП'),
        ),
        migrations.AddField(
            model_name='product',
            name='cp_notes',
            field=models.TextField(blank=True, help_text='Дополнительная информация для коммерческого предложения (производитель, коллекция и т.д.)', verbose_name='Примечание для КП'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_url',
            field=models.URLField(blank=True, help_text='URL магазина/поставщика для КП', max_length=500, verbose_name='Ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='asset_id',
            field=models.CharField(help_text='Уникальный идентификатор для ссылки в Excel', max_length=50, verbose_name='ID файла'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения изображения', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.UniqueConstraint(fields=('asset_id', 'file_type'), name='unique_asset_id_per_type'),
        ),
    ]
