# Generated by Django 5.2.7 on 2026-02-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_options_product_cp_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cp_image',
        ),
    ]
