name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - uses: actions/checkout@v3

      - name: Build ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          if [ -f package.json ]; then npm install; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
