# Generated by Django 5.2.7 on 2025-10-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_rename_qty_basketitem_quantity_remove_basket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='name',
            field=models.CharField(default='Новая корзина', max_length=255),
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
