# Generated by Django 5.2 on 2025-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baskets', '0004_basket_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='baskets.basket', verbose_name='Корзина')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Запрашивающий')),
            ],
            options={
                'verbose_name': 'Запрос на редактирование корзины',
                'verbose_name_plural': 'Запросы на редактирование корзины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='basketeditrequest',
            constraint=models.UniqueConstraint(fields=('basket', 'requester', 'status'), name='baskets_basketeditrequest_unique_basket_requester_status'),
        ),
    ]
