# Generated by Django 5.2.7 on 2026-02-23 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0005_basketeditrequest'),
        ('catalog', '0011_alter_product_options_product_cp_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('company_name', models.CharField(blank=True, help_text='Название студии или компании пользователя', max_length=255, verbose_name='Название компании/студии')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для отправки')),
                ('telegram', models.CharField(blank=True, help_text='Username или ID в Telegram', max_length=255, verbose_name='Telegram для отправки')),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=10, verbose_name='Способ отправки')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает генерации'), ('generated', 'Сгенерировано'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=15, verbose_name='Статус')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='commercial_proposals/', verbose_name='PDF файл КП')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
        migrations.RemoveConstraint(
            model_name='basketeditrequest',
            name='baskets_basketeditrequest_unique_basket_requester_status',
        ),
        migrations.AlterField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(default='Новая корзина', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='baskets.basket', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterUniqueTogether(
            name='basketeditrequest',
            unique_together={('basket', 'requester', 'status')},
        ),
        migrations.AddField(
            model_name='commercialproposalrequest',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='baskets.basket', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='commercialproposalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
